<?php
/**
 * @file
 * Code for the DrupalFR General feature.
 */

include_once 'drupalfr_general.features.inc';


/**
 * Implements hook_menu_alter().
 */
function drupalfr_general_menu_alter(&$items) {
  // Remove the default people page listing, replace the parent page callback
  // with the views settings.
  $items['admin/people/people']['access callback'] = FALSE;
  $items['admin/people']['page callback'] = $items['admin/people/advanced']['page callback'];
  $items['admin/people']['page arguments'] = $items['admin/people/advanced']['page arguments'];
  $items['admin/people']['load arguments'] = $items['admin/people/advanced']['load arguments'];
  $items['admin/people']['access callback'] = $items['admin/people/advanced']['access callback'];
  $items['admin/people']['access arguments'] = $items['admin/people/advanced']['access arguments'];
}

/**
 * Implements hook_default_search_api_server().
 */
function drupalfr_general_default_search_api_server() {
  $items = array();
  $items['solr'] = entity_create('search_api_server', array(
    'name' => 'Solr',
    'machine_name' => 'solr',
    'description' => '',
    'class' => 'search_api_solr_service',
    'options' => variable_get('drupalfr_solr_server_options', array()) + array(
      'host' => 'localhost',
      'port' => '8983',
      'path' => '/solr',
      'http_user' => '',
      'http_pass' => '',
      'excerpt' => 0,
      'retrieve_data' => 1,
      'highlight_data' => 0
    ),
    'enabled' => 1,
  ));
  return $items;
}
