# Schema for the configuration files of the Drupalfr newsletter module.

block.settings.newsletter_subscription_block:
  type: block_settings
  label: 'Newsletter subscription block settings.'
  mapping:
    account_hash:
      type: string
      label: 'Account hash'
    mailing_list_hash:
      type: string
      label: 'Mailing list hash'
    anti_spam_token:
      type: string
      label: 'Anti-spam token'
