page_alter: false
raw_names: false
error_handlers:
  1: 1
rebuild_theme: false
debug_mail_file_format: '%to-%subject-%datetime.mail.txt'
debug_mail_directory: 'temporary://devel-mails'
devel_dumper: kint_extended
_core:
  default_config_hash: 8SYa5OOpQGdg4wnttb0LFNuG6GmivsS2qNv9sTH9gDI
langcode: fr
debug_logfile: 'temporary://drupal_debug.txt'
debug_pre: false
