<?php
// $Id: rules_admin.module,v 1.1.4.5 2010/12/21 16:40:29 fago Exp $

/**
 * @file Rules Admin UI
 */

/**
 * Implements hook_entity_info_alter().
 */
function rules_admin_entity_info_alter(&$entity_info) {
  // Enable the entity API UI controller. See EntityDefaultUIController.
  $entity_info['rules_config']['admin ui'] = array(
    'controller class' => 'RulesUIController',
    'path' => 'admin/config/workflow/rules',
    'file' => 'rules_admin.inc',
    'file path' => drupal_get_path('module', 'rules_admin'),
  );
}
