<?php

/**
 * Implements hook_menu().
 */
function drupalfr_events_menu() {
  return array(
    'prochains-evenements' => array(
      'title' => 'Prochains évènements',
      'page callback' => 'drupalfr_events_upcoming_events',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function drupalfr_events_theme() {
  return array(
    'dfr_events_listing' => array(
      'variables' => array('display_mode' => NULL, 'events' => array()),
      'template' => 'drupalfr-events-listing',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function drupalfr_events_block_info() {
  return array(
    'next_events' => array(
      'info' => t('Prochains évènements Meetup'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function drupalfr_events_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'next_events':
      $events = drupalfr_events_fetch_events(6);
      $block = array(
        'subject' => t('6 prochains évènements meetup.com'),
        'content' => array(
          'events' => drupalfr_events_display_events($events, 'teaser'),
          'link' => array(
            '#markup' => l(t('Programme détaillé'), 'prochains-evenements', array(
              'attributes' => array(
                'class' => array(
                  'more-link',
                ),
              ))
            ),
          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Displays the upcoming events.
 *
 * @param array $events
 *   Array of events coming from the raw answer of meetup.com API response.
 * @param string $display_mode
 *   Display mode to choose the render format. Can be either teaser of full.
 *
 * @return array
 *   Returns a renderable array.
 */
function drupalfr_events_display_events($events, $display_mode = 'teaser') {
  $content = array();
  if ($events) {
    $content['#theme'] = 'dfr_events_listing';
    $content['#display_mode'] = $display_mode;
    $content['#events'] = $events;
  }
  else {
    $content['#markup'] = "<p>Aucun évènement n'est prévu pour le moment.</p>";
  }
  return $content;
}

/**
 * Fetch the upcoming events from Meetup.com API.
 *
 * @param mixed $items
 *   Number of items to extract from the feed. If not provided, all the meetups
 *   will be fetched.
 *
 * @return mixed
 *   Returns FALSE if the feed is down or doesn't have any upcoming event.
 *   Returns the raw array of the upcoming events extracted from
 *   meetup.com API response.
 */
function drupalfr_events_fetch_events($items = FALSE) {
  $query_url = 'https://api.meetup.com/2/events?key=4051646f3d23a6114243d5834497d&sign=true&status=upcoming&group_urlname=drupal-france-francophonie';
  if ($items) {
    $query_url .= '&page=' . $items;
  }
  $response = drupal_http_request($query_url);
  if ($response->code == 200) {
    // Extract the response data.
    $data = drupal_json_decode($response->data);
    if (count($data['results']) > 0) {
      return $data['results'];
    }
    else {
      return FALSE;
    }
  }
  else {
    watchdog('events_meetup', 'Error parsing the meetup feed. @response', array('@response' => $response));
    return FALSE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Exposes the display mode as an extra class.
 */
function drupalfr_events_preprocess_dfr_events_listing($variables) {
  $variables['classes'] = implode(' ', array('drupalfr-events-list', $variables['display_mode']));
}


/**
 * Page callback for prochains-evenements.
 */
function drupalfr_events_upcoming_events() {
  if ($content = cache_get('upcoming-events-full')) {
    return $content->data;
  }
  else {
    $events = drupalfr_events_fetch_events();
    $map = leaflet_map_get_info('OSM Mapnik');
    $features = drupalfr_events_prepare_leaflet_features($events);

    // Keep only 5 meetups for the list.
    $list_events = array_slice($events, 0, 5);

    $content['map'] = leaflet_build_map($map, $features, '600px');
    $content['events'] = drupalfr_events_display_events($list_events, 'full');
    $content['infos'] = array(
      '#markup' => '<p>' . l(t('Voir tous les évènements'), 'http://www.meetup.com/drupal-france-francophonie') . '</p>',
    );
    cache_set('upcoming-events-full', $content, 'cache', 3600);
    return $content;
  }
}

/**
 * Helper function.
 *
 * Prepare leaflet features from meetups events.
 *
 * @param array $events
 *   An array of events from meetup as retrieved with
 *   drupalfr_events_fetch_events().
 *
 * @return array
 *   An array of leaflet features to give to leaflet_render_map().
 */
function drupalfr_events_prepare_leaflet_features($events) {
  $features = array();

  foreach ($events as $event) {
    if (isset($event['venue'])) {
      $features[] = array(
        'type' => 'point',
        'lat' => $event['venue']['lat'],
        'lon' => $event['venue']['lon'],
        'popup' => l($event['name'], $event['event_url'], array('absolute' => TRUE)),
      );
    }
  }

  return $features;
}
