<?php

/**
 * @file
 * Contains hook implementations for drupalfr_core module.
 */

/**
 * Implements hook_leaflet_map_info_alter().
 */
function drupalfr_core_leaflet_map_info_alter(array &$map_info) {
  // Alter default leaflet map globally.
  // Set default zoom and maxBounds.
  // Disable zoom.
  $map_info['OSM Mapnik']['settings']['touchZoom'] = FALSE;
  $map_info['OSM Mapnik']['settings']['scrollWheelZoom'] = FALSE;
  $map_info['OSM Mapnik']['settings']['doubleClickZoom'] = FALSE;
  $map_info['OSM Mapnik']['settings']['zoomControl'] = FALSE;
  $map_info['OSM Mapnik']['settings']['zoom'] = 5;
  $map_info['OSM Mapnik']['settings']['maxBounds'] = [
    ['lat' => '40.613952441166596', 'lng' => '11.2445068359375'],
    ['lat' => '52.05249047600099', 'lng' => '-7.80029296875'],
  ];
}
