<?php
// $Id$

include_once dirname(__FILE__) . '/drupalfr_workflow.features.inc';

/**
 * Implementation of hook_flag_default_flags().
 */
function drupalfr_workflow_flag_default_flags() {
  $flags = array();
  // Exported flag: "Réponse acceptée".
  $flags[] = array(
    'content_type' => 'comment',
    'name' => 'accepted_answer',
    'title' => 'Réponse acceptée',
    'global' => '1',
    'types' => array(
      0 => 'forum',
    ),
    'flag_short' => 'accepter cette réponse',
    'flag_long' => '',
    'flag_message' => '',
    'unflag_short' => 'rejeter cette réponse',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'confirm',
    'roles' => array(
      'flag' => array(
        0 => '2',
      ),
      'unflag' => array(
        0 => '2',
      ),
    ),
    'access_author' => '',
    'show_on_comment' => 1,
    'flag_confirmation' => 'Êtes vous sûr de vouloir accepter cette réponse ?',
    'unflag_confirmation' => 'Êtes vous sûr de vouloir rejeter cette réponse ?',
    'api_version' => 2,
  );
  return $flags;
}

/**
 * Implementation of hook_flag_access().
 */
function drupalfr_workflow_flag_access($flag, $content_id, $action, $account) {
  global $user;
  if ($flag->name == 'accepted_answer') {
    $comment = $flag->fetch_content($content_id);
    $node = node_load($comment->nid);

    // User can edit that flag if
    //  - it is the owner of the node and not the owner of the comment.
    //  - and this node doesn't have an accepted answer or the comment is accepted.
    if (($node->uid == $user->uid) && ($comment->uid != $user->uid) &&
        ((isset($node->field_workflow_status[0]['value']) && ($node->field_workflow_status[0]['value'] == 'pending')) || $flag->is_flagged($content_id))) {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }
}

/**
 * Implementation of hook_field_access().
 *
 * Hide the Workflow status field from innocent eyes.
 */
function drupalfr_workflow_field_access($op, $field, $account, $node = NULL) {
  if (($op == 'edit') && ($field['field_name'] == 'field_workflow_status') && !user_access('administer nodes', $account)) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Implementation of hook_menu_alter().
 */
function drupalfr_workflow_menu_alter(&$items) {
  $items['myuserpoints']['access callback'] = 'user_access';
  $items['myuserpoints']['access arguments'] = array(USERPOINTS_PERM_ADMIN);
  $items['userpoints']['access callback'] = 'user_access';
  $items['userpoints']['access arguments'] = array(USERPOINTS_PERM_ADMIN);
}

/**
 * Load flagged content when displaying the node.
 */
function drupalfr_workflow_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  if ($op == 'view' && $node->type == 'forum') {
    $node->flagged_comments = array();
    $flag = flag_get_flag('accepted_answer');
    $result = db_query("SELECT fc.* FROM {comments} c INNER JOIN {flag_content} fc ON (fc.content_type = 'comment' AND fc.content_id = c.cid) WHERE c.nid = %d AND fc.fid = %d", $node->nid, $flag->fid);
    while ($flagged_comment = db_fetch_object($result)) {
      $node->flagged_comments[$flagged_comment->content_id] = TRUE;
    }
  }

  if ($op == 'update') {
    // Prevent notifications on all content updates.
    $node->notifications_content_disable = TRUE;
  }
}
