views.argument_validator.drupalfr_user_role:
  type: mapping
  label: 'User role (Drupalfr)'
  mapping:
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role ID'
