<?php

function drupalfr_spam_form_user_register_alter(&$form, &$form_state) {
  drupal_add_css(drupal_get_path('module', 'drupalfr_spam') . '/drupalfr_spam.css');
  $form['coupon_control'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#description' => t('Do not fill this field.'),
    '#element_validate' => array('drupalfr_spam_element_validate'),
  );
}

function drupalfr_spam_element_validate($element) {
  if (!empty($element['#value'])) {
    form_error($element, t('This field has to be empty.'));
  } 
}

