<?php

/**
 * @file
 * Contains hook implementations for drupalfr_social module.
 */

/**
 * Implements hook_theme().
 */
function drupalfr_social_theme($existing, $type, $theme, $path) {
  return [
    'drupalfr_social_twitter_statuses' => [
      'variables' => [
        'statuses' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_drupalfr_social_twitter_statuses().
 */
function drupalfr_social_preprocess_drupalfr_social_twitter_statuses(&$variables) {
  /** @var Drupal\Core\Datetime\DateFormatterInterface $date_formatter */
  $date_formatter = \Drupal::service('date.formatter');

  foreach ($variables['statuses'] as $key => $status) {
    // Format creation date.
    $created_at = \DateTime::createFromFormat('D M d H:i:s O Y', $variables['statuses'][$key]->created_at);
    $variables['statuses'][$key]->created_at = $date_formatter->format($created_at->getTimestamp(), 'long');

    // Format tweet text.
    $variables['statuses'][$key]->text = check_markup($variables['statuses'][$key]->text, 'restricted_html');
  }
}
