<?php
/**
 * @file
 * Code for the Drupalfr search feature.
 */

include_once 'drupalfr_search.features.inc';


/**
 * Implements hook_default_search_api_server().
 */
function drupalfr_search_default_search_api_server() {
  $items = array();
  $items['solr'] = entity_create('search_api_server', array(
    'name' => 'Solr',
    'machine_name' => 'solr',
    'description' => '',
    'class' => 'search_api_solr_service',
    'options' => variable_get('drupalfr_solr_server_options', array()) + array(
      'host' => 'localhost',
      'port' => '8983',
      'path' => '/solr',
      'http_user' => '',
      'http_pass' => '',
      'excerpt' => 1,
      'retrieve_data' => 1,
      'highlight_data' => 0
    ),
    'enabled' => 1,
  ));
  return $items;
}

/**
 * Implements hook_theme().
 */
function drupalfr_search_theme() {
  return array(
    'drupalfr_search_form' => array(
      'render element' => 'form',
      'template' => 'search-block-form',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function drupalfr_search_block_info() {
  $blocks = array();
  $blocks['solr-search'] = array(
    'info' => t('Recherche solr'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function drupalfr_search_block_view($delta) {
  $block = array();
  $block['subject'] = t('Rechercher');
  $block['content'] = drupal_get_form('drupalfr_search_form');
  return $block;
}


/**
 * Display a search form.
 */
function drupalfr_search_form(array $form, array &$form_state) {
  $form['keys'] = array(
    '#type' => 'textfield',
    '#size' => 15,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  return $form;
}

/**
 * Validation callback for drupalfr_search_form().
 */
function drupalfr_search_form_validate(array $form, array &$form_state) {
  if (!trim($form_state['values']['keys'])) {
    form_set_error('keys', t('Please enter at least one keyword.'));
  }
}

/**
 * Submit callback for drupalfr_search_form().
 */
function drupalfr_search_form_submit(array $form, array &$form_state) {
  $keys = trim($form_state['values']['keys']);
  $q = array('search_api_views_fulltext' => $keys);
  $q += drupal_get_query_parameters();
  drupal_goto('recherche', array('query' => $q));
}
