drupalfr_localize_statistics.localize_statistics_type.*:
  type: config_entity
  label: 'Statistique de la traduction type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
