<?php

/**
 * @file
 * Contains hook implementations for drupalfr_newsletter module.
 */

define('DRUPALFR_NEWSLETTER_DEFAULT_ACCOUNT_HASH', 'eb7ebedd32b3b2fc0ac192ee9');
define('DRUPALFR_NEWSLETTER_DEFAULT_MAILING_LIST_HASH', '27e99cb1af');
define('DRUPALFR_NEWSLETTER_DEFAULT_ANTI_SPAM_TOKEN', 'b_eb7ebedd32b3b2fc0ac192ee9_27e99cb1af');

/**
 * Implements hook_theme().
 */
function drupalfr_newsletter_theme($existing, $type, $theme, $path) {
  return [
    'drupalfr_newsletter_subscription_block' => [
      'variables' => [
        'account_hash' => DRUPALFR_NEWSLETTER_DEFAULT_ACCOUNT_HASH,
        'mailing_list_hash' => DRUPALFR_NEWSLETTER_DEFAULT_MAILING_LIST_HASH,
        'anti_spam_token' => DRUPALFR_NEWSLETTER_DEFAULT_ANTI_SPAM_TOKEN,
      ],
    ],
  ];
}
