favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://127.0.0.1:8100/themes/custom/drupalfr_theme/favicon.ico'
  use_default: true
schema: '8000'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  navigation_collapsible_mobile_user: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  footer_col_1: ''
  footer_col_2: ''
  footer_col_3: ''
navbar_position: fixed-top
breadcrumb_home: 1
forms_smart_descriptions: 0
schemas:
  bootstrap: 8000
  drupalfr_theme: 8000
table_responsive: '-1'
table: ''
cdn_provider: ''
navbar_inverse: 1
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
langcode: fr
_core:
  default_config_hash: tbGH3KubvM14kUS6eoep8Bwxw6MvopeHP1LC9gyxFLs
