_core:
  default_config_hash: 7R74wb0NllX6DTTAV9sfg790XV_QXshmF0wAobLEFNQ
langcode: fr
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: ''
classic_toolbar: horizontal
high_contrast_mode: false
accent_color: ''
focus_color: ''
show_user_theme_settings: true
icon_default: true
icon_path: ''
icon_upload: ''
