unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_attendance_certificate_form: true
  contact_message_contact_form: true
  contact_message_personal_form: false
  contact_message_sponsor_form: true
  contact_message_volunteer_form: true
  node_type_node_form: false
langcode: fr
_core:
  default_config_hash: PKDv0__gzFUTJ2VExiaXAWD9BK6h3quJSJx5jWB-1DU
