_core:
  default_config_hash: 5EF_vBR8XTavQvYZXKvZgLlSM0NHXbQ7UO4hcjWuKdc
langcode: fr
theme: current
defaults:
  sender: php_mail
  formatter: php_mail
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
  commerce_order:
    receipt:
      sender: swiftmailer
      formatter: swiftmailer
