_core:
  default_config_hash: 0f9QAstx6Dyy5Z49L0a6pO8MlIl1SNBalUWB9lGnzj8
langcode: fr
display_denied_message: true
access_denied_message: 'Accès refusé. Vous devez vous authentifier pour visualiser cette page.'
access_denied_message_type: error
redirect_authenticated_users_to: ''
user_login_path: /user/login
default_redirect_code: 302
destination_parameter_override: ''
match_noredirect_pages: ''
redirect_to_destination: true
