<?php
/**
 * @file
 * Code for the Drupal FR planete feature.
 */

include_once('drupalfr_planete.features.inc');

/**
 * Ensures that the feed exist.
 */
function _drupalfr_planete_user_save($account) {
  // Avoid some PHP warnings if site is broken.
  if (isset($account->field_planete_rss) &&
      !empty($account->field_planete_rss) &&
      // For the first time in my life I have the pleasure to see the field
      // API leaving an empty value in there, so I have to do deeper checks
      // than usual to ensure we have no URL.
      isset($account->field_planete_rss[LANGUAGE_NONE][0]['url']))
  {
    $feed_url = $account->field_planete_rss[LANGUAGE_NONE][0]['url'];

    $nid = db_select('node', 'n')
       ->fields('n', array('nid'))
       ->condition('n.type', 'planete_feed_source')
       ->condition('n.uid', $account->uid)
       ->range(0, 1)
       ->execute()
       ->fetchField();

    if ($nid) {
      // Node might be updated from here.
      $node = node_load($nid);

      if ($feed_url !== $node->feeds['FeedsHTTPFetcher']['source']) {
        // URL changed, update the node.
        $node->feeds = array(
          'FeedsHTTPFetcher' => array(
            'source' => $feed_url,
          ),
        );
        node_save($node);
      }
    } else {
      // Create new node.
      $node = new stdClass;
      $node->title = "Planète pour l'utilisateur " . $account->uid;
      $node->type = 'planete_feed_source';
      $node->feeds = array(
        'FeedsHTTPFetcher' => array(
          'source' => $feed_url,
        ),
      );
      $node->status = 1;
      $node->uid = $account->uid;
      node_save($node);
    }
  } else {
    // No feed set or has been removed.
    $nid_list = db_select('node', 'n')
      ->fields('n', array('nid'))
      ->condition('n.type', 'planete_feed_source')
      ->condition('n.uid', $account->uid)
      ->execute()
      // Doing a fetchCol() and no LIMIT clause will ensure that in case
      // a bug happened and user more than one feed source, we delete them
      // all.
      ->fetchCol();

    node_delete_multiple($nid_list);
  }
}

/**
 * Implements hook_user_insert().
 */
function drupalfr_planete_user_insert($edit, $account) {
  _drupalfr_planete_user_save($account);
}

/**
 * Implements hook_user_update().
 */
function drupalfr_planete_user_update($edit, $account) {
  _drupalfr_planete_user_save($account);
}
