<?php

module_load_include('inc', 'pathauto', 'pathauto');

$result = db_query("SELECT n.nid FROM {node} n WHERE n.type = '%s' ORDER BY n.nid", 'forum');

$has_processed = FALSE;
while ($node = db_fetch_object($result)) {
  $node = node_load($node->nid, NULL, TRUE);
  $placeholders = pathauto_get_placeholders('node', $node);
  if ($alias = pathauto_create_alias('node', 'bulkupdate', $placeholders, "node/$node->nid", $node->nid, $node->type, $node->language)) {
    echo ".";
  }
}
