# Schema for the configuration files of the Drupalfr social module.

drupalfr_social.twitter:
  type: config_object
  label: 'Settings for Twitter connection'
  mapping:
    consumer_key:
      type: string
      label: 'Consumer key'
    consumer_secret:
      type: string
      label: 'Consumer secret'
    access_token:
      type: string
      label: 'Access token'
    access_token_secret:
      type: string
      label: 'Access token secret'

field.formatter.settings.drupalfr_social_twitter_feed:
  type: mapping
  label: 'Twitter feed formatter settings'
