<?php

include_once('drupalfr_user.features.inc');

/**
 * Implementation of hook_form_alter().
 */
function drupalfr_user_form_profile_node_form_alter(&$form, $form_state) {
  $form['title']['#access'] = FALSE;
  $form['title']['#element_validate'] = array('_drupalfr_user_profile_set_title');
  $form['body_field']['body']['#rows'] = 4;
}

/**
 * Implementation of hook_menu_alter().
 */
function drupalfr_user_menu_alter(&$items) {
  // Fix a bug in tab visibility.
  $items['user/%user/edit'] = $items['user/%user_category/edit'];
  unset($items['user/%user_category/edit']);
  $items['user/%user/edit']['title'] = 'My account';
  $items['user/%user/profile/profile']['title'] = 'My profile';
  $items['user/%user/profile/profile']['title callback'] = 't';
}

/**
 * Element validate function to set the title of the profile to a default value.
 */
function _drupalfr_user_profile_set_title($element, &$form_state) {
  $form_state['values']['title'] = '#' . $form_state['values']['uid'];
}

/**
 * Implementation of hook_init().
 *
 * Redirect node profiles to the user page.
 */
function drupalfr_user_init() {
  if ($node = menu_get_object()) {
    if ($node->type == 'profile') {
      drupal_goto('user/' . $node->uid);
    }
  }
}
