<?php

/**
 * @file
 * Contains hook implementations for drupalfr_paragraph module.
 */

use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;

/**
 * Implements hook_preprocess_paragraph().
 */
function drupalfr_paragraph_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->bundle() == 'banner') {

    // Allow to wrap the paragraph into a link.
    if ($paragraph->hasField('field_banner_link')) {
      $banner_link = $paragraph->get('field_banner_link')->getValue();

      if (!empty($banner_link)) {
        $variables['banner_link_url'] = Url::fromUri($banner_link[0]['uri'])->toString();
        $variables['banner_link_title'] = $banner_link[0]['title'];
      }
    }

    // Prepare Banner image to be display as a background.
    if ($paragraph->hasField('field_media')) {
      $banner_media = $paragraph->get('field_media')->getValue();

      if (!empty($banner_media)) {
        $media = Media::load($banner_media[0]['target_id']);

        if (!is_null($media) && $media->hasfield('field_media_image')) {
          $banner_image = $media->get('field_media_image')->getValue();

          if (!empty($banner_image)) {
            $banner_image_file = File::load($banner_image[0]['target_id']);

            if (!is_null($banner_image_file)) {
              $variables['banner_media'] = file_url_transform_relative(file_create_url($banner_image_file->getFileUri()));
            }
          }
        }
      }
    }
  }
}
