# Schema for the configuration files of the Drupalfr release module.

drupalfr_release.settings:
  type: config_object
  label: 'Settings for Release'
  mapping:
    xml_address:
      type: string
      label: 'XML address'
