<?php

/**
 * @file
 * Contains hook implementations for drupalfr_media module.
 */

/**
 * Implements hook_preprocess_views_view().
 */
function drupalfr_media_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'media_browser') {
    $variables['view_array']['#attached']['library'][] = 'media_entity_browser/view';
    $variables['view_array']['#attached']['library'][] = 'drupalfr_media/view';
  }
}
