<?php

/**
 * Implements hook_block_info().
 */
function dfr_blocks_block_info() {
  $blocks = array();

  $blocks['home_events'] = array(
    'info' => "DrupalFR : Home Evenements",
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['home_help'] = array(
    'info' => "DrupalFR : Home Aide",
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['home_trad'] = array(
    'info' => "DrupalFR : Home Traduction",
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  $blocks['download'] = array(
    'info' => "DrupalFR : Télechargement",
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['about_us'] = array(
    'info' => "DrupalFR : Qui sommes nous",
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['twitter_asso'] = array(
    'info' => "DrupalFR : Twitter #drupalfr",
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dfr_blocks_block_view($delta = '') {
  switch($delta) {

    // Homepage.
    case 'home_events':
      return dfr_blocks_block_home_events();
      break;
    case 'home_help':
      return dfr_blocks_block_home_help();
      break;
    case 'home_trad':
      return dfr_blocks_block_home_trad();
      break;

    // Téléchargement.
    case 'download':
      return dfr_blocks_block_download();
      break;
    // Qui sommes nous.
    case 'about_us':
      return dfr_blocks_block_about_us();
      break;
    // Twitter asso.
    case 'twitter_asso':
      return dfr_blocks_block_twitter_asso();
      break;
  }
}

/**
 * Implements hook_block_configure().
 */
function dfr_blocks_block_configure($delta = '') {
  $form = array();
  if ($delta == 'home_events') {
    $form['home_events_content'] = array(
      '#type' => 'text_format',
      '#title' => t('Content'),
      '#default_value' => variable_get(
        'home_events_content',
        array('value' => '', 'format' => filter_fallback_format())
      ),
    );
  }
  elseif ($delta == 'home_help') {
    $form['home_help_content'] = array(
      '#type' => 'text_format',
      '#title' => t('Content'),
      '#default_value' => variable_get(
        'home_help_content',
        array('value' => "", 'format' => filter_fallback_format())
      ),
    );
  }
  elseif ($delta == 'home_trad') {
    $form['home_trad_content'] = array(
      '#type' => 'text_format',
      '#title' => t('Content'),
      '#default_value' => variable_get(
        'home_trad_content',
        array('value' => "", 'format' => filter_fallback_format())
      ),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function dfr_blocks_block_save($delta = '', $edit = array()) {
  if ($delta == 'home_events') {
    variable_set('home_events_content', $edit['home_events_content']);
  }
  elseif ($delta == 'home_help') {
    variable_set('home_help_content', $edit['home_help_content']);
  }
  elseif ($delta == 'home_trad') {
    variable_set('home_trad_content', $edit['home_trad_content']);
  }
}

/** ******************************************************* **/
/** Callback functions                                      **/
/** ******************************************************* **/

function dfr_blocks_block_home_events() {
  $content = variable_get(
    'home_events_content',
    array('value' => "Trouvez la date du prochain évènement durant lequel vous pourrez rencontrer les membres de la communauté proches de chez vous.", 'format' => NULL)
  );
  return array(
    'subject' => "Évènements",
    'content' => array(
      'text' => array('#markup' => check_markup($content['value'], $content['format'])),
      'link' => array(
        '#theme' => 'link',
        '#text' => "Programme détaillé",
        '#path' => 'prochains-evenements',
        '#options' => array(
          'attributes' => array('class' => array('btn-link')),
          'html' => FALSE,
        ),
      ),
    ),
  );
}

function dfr_blocks_block_home_help() {
  $content = variable_get(
    'home_help_content',
    array('value' => "Trouvez comment obtenir de l'information sur le fonctionnement de Drupal et demander de l'aide via nos moyens de communication.", 'format' => NULL)
  );
  return array(
    'subject' => "Aide",
    'content' => array(
      'text' => array('#markup' => check_markup($content['value'], $content['format'])),
      'link' => array(
        '#theme' => 'link',
        '#text' => "En savoir plus",
        '#path' => 'node/705',
        '#options' => array(
          'attributes' => array('class' => array('btn-link')),
          'html' => FALSE,
        ),
      ),
    ),
  );
}

function dfr_blocks_block_home_trad() {
  $content = variable_get(
    'home_trad_content',
    array('value' => "Découvrez comment installer et traduire Drupal en français grâce à la traduction maintenue par l'équipe de Drupalfr.org.", 'format' => NULL)
  );
  return array(
    'subject' => "Traduction",
    'content' => array(
      'text' => array('#markup' => check_markup($content['value'], $content['format'])),
      'link' => array(
        '#theme' => 'link',
        '#text' => "En savoir plus",
        '#path' => 'node/695',
        '#options' => array(
          'attributes' => array('class' => array('btn-link')),
          'html' => FALSE,
        ),
      ),
    ),
  );
}

function dfr_blocks_block_download() {
  $current_version = 'Drupal ' . variable_get('drupalfr_current_version', 7) . ' [FR]';
  $previous_version = 'Drupal ' . variable_get('drupalfr_previous_version', 6) . ' [FR]';
  $items = array(
    'drupal_current' => $current_version . l(t('Télécharger'), file_create_url('public://drupal-7.latest.tar.gz'), array('attributes' => array('class' => 'btn-link'))),
    'drupal_previous' => $previous_version . l(t('Télécharger'), file_create_url('public://drupal-6.latest.tar.gz'), array('attributes' => array('class' => 'btn-link'))),
  );
  return array(
    'subject' => "Obtenir la dernière version",
    'content' => array(
      '#theme' => 'item_list',
      '#items' => $items,
    ),
  );
}

function dfr_blocks_block_about_us() {
  $content = '<p>';
  $content .= 'Drupalfr.org offre des services à la communauté Drupal française et francophone. Notre site est opéré et géré par une petite équipe de bénévoles.';
  $content .= '</p>';
  return array(
    'subject' => "Qui sommes-nous ?",
    'content' => array(
      'text' => array(
        '#markup' => $content,
      ),
      'link' => array(
        '#theme' => 'link',
        '#text' => "En savoir plus",
        '#path' => 'association',
        '#options' => array(
          'attributes' => array('class' => array('btn-link')),
          'html' => FALSE,
        ),
      ),
      'link_2' => array(
        '#theme' => 'link',
        '#text' => "Nous contacter",
        '#path' => 'contact',
        '#options' => array(
          'attributes' => array('class' => array('btn-link')),
          'html' => FALSE,
        ),
      ),
    ),
  );
}

function dfr_blocks_block_twitter_asso() {
  $content = twitter_pull_render('#drupalfr');
  return array(
    'subject' => "Twitter #drupalfr",
    'content' => array(
      'text' => array(
        '#markup' => $content,
      ),
      'link' => array(
        '#theme' => 'link',
        '#text' => "Compte @drupalfr",
        '#path' => 'http://twitter.com/drupalfr',
        '#options' => array(
          'attributes' => array('class' => array('btn-link')),
          'html' => FALSE,
          'absolute' => TRUE,
        ),
      ),
    ),
  );
}

/**
 * Implements hook_block_view_alter().
 *
 * Add drupalfr link to twitter blocks.
 */
function dfr_blocks_block_view_alter(&$data, $block) {
  if ($block->module == 'twitter_block') {
    $data['content'] = array('original_content' => $data['content']);
    $data['content']['link'] = array(
      '#theme' => 'link',
      '#text' => "Compte @drupalfr",
      '#path' => 'http://twitter.com/drupalfr',
      '#options' => array(
        'attributes' => array('class' => array('btn-link')),
        'html' => FALSE,
        'absolute' => TRUE,
      ),
    );
  }
}
