<?php

/**
 * @file
 * Install, update and uninstall functions for the commentrss module.
 */

/**
 * Implements hook_uninstall().
 */
function commentrss_uninstall() {
  // Delete all variables.
  variable_del('commentrss_site');
  variable_del('commentrss_node');
  variable_del('commentrss_term');
}

/**
 * Empty update since menu items have changed.
 */
function commentrss_update_6200() {
  return array();
}
