<?php

/**
 * @file
 *   Publishes RSS feeds for comments.
 */

/**
 * Disable site comment feed.
 */
define('COMMENTRSS_SITE_DISABLED', 0);

/**
 * Expose site feed on front page only.
 */
define('COMMENTRSS_SITE_FRONT_PAGE', 1);

/**
 * Expose site feed on front page and main content (/node) page too.
 */
define('COMMENTRSS_SITE_FRONT_AND_NODE_PAGE', 2);

/**
 * Expose site feed on all pages.
 */
define('COMMENTRSS_SITE_ALL_PAGES', 3);

// Backport of the PHP 5.1.1 and above DATE_RSS date constant.
if (!defined('DATE_RSS')) {
  define('DATE_RSS', 'D, d M Y H:i:s O');
}

// == Core hooks ===============================================================

/**
 * Implements hook_help().
 */
function commentrss_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#commentrss':
      $output = '<p>' . t('The commentrss module provides RSS feeds for comments. Comment feeds are published on pages which often also provide a feed of nodes. Some types of comment feeds may be disabled if they are not needed.') . '</p>';
      $output .= '<p>' . t('If comment feeds are enabled for individual nodes then a "wfw:commentRss" element is added to node feeds (based on <a href="@wfw">the Well Formed Web Comment API</a> specification) so that aggregators may discover the corresponding comment feed.', array('@wfw' => 'http://wellformedweb.org/CommentAPI/')) . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_menu().
 */
function commentrss_menu() {
  // Copy of menu item from system.module.
  $items['admin/content/rss-publishing/default'] = array(
    'title' => 'General settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file path' => drupal_get_path('module', 'system'),
  );
  // New local task on the RSS publishing settings page.
  $items['admin/content/rss-publishing/commentrss'] = array(
    'title' => 'Comment RSS settings',
    'description' => 'Configure RSS feeds for comments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commentrss_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
    'file' => 'commentrss.admin.inc',
  );

  // RSS callback handlers
  $items['crss'] = array(
    'page callback' => 'commentrss_feed_site',
    'access arguments' => array('access comments'),
    'type' => MENU_CALLBACK,
    'file' => 'commentrss.pages.inc',
  );
  $items['crss/node/%node'] = array(
    'page callback' => 'commentrss_feed_node',
    'page arguments' => array(2),
    'access callback' => 'commentrss_node_feed_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'commentrss.pages.inc',
  );

  return $items;
}

/**
 * Access callback; determines if the user can access a node's comment RSS.
 */
function commentrss_node_feed_access($node, $check_view_access = TRUE) {
  return $node->comment != COMMENT_NODE_DISABLED && variable_get('commentrss_node', TRUE) && user_access('access comments') && (!$check_view_access || node_access('view', $node));
}

/**
 * Implements hook_preprocess_page().
 */
function commentrss_preprocess_page(&$variables) {
  // This hook gets called for offline pages and breaks the theme, so
  // skip running in that case to avoid interfering with that operation.
  // We no longer need to check if !variable_get('site_offline', 0) since
  // this preprocess functions is never called for offline pages.
  if (!user_access('access comments') || arg(0) == 'admin') {
    return;
  }

  // Expose site feed based on settings.
  switch (variable_get('commentrss_site', COMMENTRSS_SITE_FRONT_PAGE)) {
    case COMMENTRSS_SITE_DISABLED:
      // No comment RSS feed for site.
      break;
    case COMMENTRSS_SITE_FRONT_PAGE:
      if (!drupal_is_front_page()) {
        // Only break if not front page.
        break;
      }
    case COMMENTRSS_SITE_FRONT_AND_NODE_PAGE:
      if (!drupal_is_front_page() || ($_GET['q'] != 'node')) {
        // Only break if not front page and not node page.
        break;
      }
    case COMMENTRSS_SITE_ALL_PAGES:
      // Either we need to expose for all pages, or code was falling through
      // to this point. We should expose the feed in any case.
      drupal_add_feed(
        url('crss', array('absolute' => TRUE)),
        t('@site - All comments', array('@site' => variable_get('site_name', 'Drupal')))
      );

      // Replace the head and feed icons variable with our new feeds.
      $variables['head'] = drupal_get_html_head();
      $variables['feed_icons'] = drupal_get_feeds();
      break;
  }
}

/**
 * Implements hook_nodeapi().
 */
function commentrss_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  if ($op == 'view' && $page && commentrss_node_feed_access($node, FALSE)) {
    // Expose node's comment feed on node view page.
    drupal_add_feed(
      url('crss/node/' . $node->nid, array('absolute' => TRUE)),
      t('Comments for "@title"', array('@title' => $node->title))
    );
  }
  if ($op == 'rss item' && commentrss_node_feed_access($node, FALSE)) {
    // Add a wfw:commentRss element to the node when viewed in a node RSS feed.
    return array(array(
      'key' => 'wfw:commentRss',
      'value' => url('crss/node/' . $node->nid, array('absolute' => TRUE)),
      'namespace' => array(
        'xmlns:wfw' => 'http://wellformedweb.org/CommentAPI/',
      ),
    ));
  }
}
