<?php
/**
 * @file
 * Code for the dfr_emploi feature.
 */

include_once 'dfr_emploi.features.inc';

/**
 * Implements hook_form_alter().
 */
function dfr_emploi_form_offre_node_form_alter(&$form, &$form_state) {
  $form['scheduler_settings']['unpublish_on']['#description'] .= " La limite de publication d'une offre est fixée à 6 mois maximum.";
  $form['#validate'][] = 'dfr_emploi_unpublishing_date_validate';
}

/**
 * Validate handler to check for unpublishing date on offre
 */
function dfr_emploi_unpublishing_date_validate($form, &$form_state) {
  $unpublish_time = _scheduler_strtotime($form_state['values']['unpublish_on']);
  if ($unpublish_time > REQUEST_TIME + 3600 * 24 * 30 * 6) {
    form_set_error('unpublish_on', 'On a dit 6 mois !');
  }
}

/**
 * Implements hook_node_access().
 */
function dfr_emploi_node_access($node, $op, $account) {
  if ($op == 'update' && $node->type == 'offre' && $node->status) {
    if (!user_access('administer content', $account) && ($account->uid == $node->uid)) {
      drupal_set_message('Cette offre est publiée et ne peut plus être modifiée.');
      return NODE_ACCESS_DENY;
    }
  }

  // Returning nothing from this function would have the same effect.
  return NODE_ACCESS_IGNORE;
}
