<?php

/**
 * @file
 * Contains hook implementations for drupalfr_core module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\node\NodeInterface;

/**
 * Implements hook_leaflet_map_info_alter().
 */
function drupalfr_core_leaflet_map_info_alter(array &$map_info) {
  // Alter default leaflet map globally.
  // Set default zoom and maxBounds.
  // Disable zoom.
  $map_info['OSM Mapnik']['settings']['touchZoom'] = FALSE;
  $map_info['OSM Mapnik']['settings']['scrollWheelZoom'] = FALSE;
  $map_info['OSM Mapnik']['settings']['doubleClickZoom'] = FALSE;
  $map_info['OSM Mapnik']['settings']['zoomControl'] = FALSE;
  $map_info['OSM Mapnik']['settings']['zoom'] = 5;
  $map_info['OSM Mapnik']['settings']['maxBounds'] = [
    ['lat' => '48.8566969', 'lng' => '2.3514616'],
    ['lat' => '52.05249047600099', 'lng' => '-7.80029296875'],
  ];
}

/**
 * Implements hook_node_presave().
 *
 * Basic implementation of "Views Custom Cache Tag".
 */
function drupalfr_core_node_presave(NodeInterface $node) {
  $cache_tag = 'node:type:' . $node->getType();
  Cache::invalidateTags([$cache_tag]);
}

/**
 * Implements hook_node_delete().
 *
 * See https://www.drupal.org/node/2917531.
 */
function drupalfr_core_node_delete(NodeInterface $node) {
  $cache_tag = 'node:type:' . $node->getType();
  Cache::invalidateTags([$cache_tag]);
}
