<?php

function drupalfr_add_block($block) {
  db_query("INSERT INTO {boxes} (body, info, format) VALUES ('%s', '%s', %d)", $block['body'], $block['info'], $block['format']);
  $delta = db_last_insert_id('boxes', 'bid');
  
  foreach (list_themes() as $key => $theme) {
    if ($theme->status) {
      db_query("INSERT INTO {blocks} (visibility, pages, custom, title, module, theme, status, weight, delta, cache) VALUES(%d, '%s', %d, '%s', '%s', '%s', %d, %d, '%s', %d)", $block['visibility'], trim($block['pages']), $block['custom'], $block['title'], 'block', $theme->name, 1, 0, $delta, BLOCK_NO_CACHE);
    }
  }
}

/**
 * Implementation of hook_menu().
 */
function drupalfr_specific_menu() {
  $items['drupalfr/front'] = array(
    'title' => 'Drupalfr.org',
    'page callback' => 'drupalfr_specific_front_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function drupalfr_specific_views_api() {
  return array('api' => 2.0);
}

/**
 * Menu callback; front page.
 */
function drupalfr_specific_front_page() {
  return "test";
}

/**
 * Implements hook_block().
 */
function drupalfr_specific_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => 'Twitter DFR',
    );
    return $blocks;
  }
  else if ($op == 'view') {
    if ($delta == 0) {
      $block['title'] = 'Twitter #drupalfr';
      $content = twitter_pull_render('drupalfr', '', 10);
      $block['content'] = $content;
      return $block;
    }
  }
}
