<?php

/**
 * Implements hook_menu().
 */
function dfr_migration_menu() {
  return array(
    'admin/migration' => array(
      'title' => 'Migration User',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('dfr_migration_admin_migrate_users'),
      'access arguments' => array('administer users'),
    ),
  );
}

/**
 * Display a form to migrate users.
 */
function dfr_migration_admin_migrate_users($form, $form_state) {
  $form['submit']['#type'] = 'submit';
  $form['submit']['#value'] = t('Migrer les profils utilisateurs');
  return $form;
}

/**
 * Submit callback settings the batch.
 */
function dfr_migration_admin_migrate_users_submit($form, $form_state) {
  $batch = array(
    'operations' => array(
      array('dfr_migration_migrate_profiles_batch', array()),
    ),
    'finished' => 'dfr_migration_migrate_profiles_batch_finished',
    'title' => t('Migrating users'),
    'init_message' => t('Préparation de la migration des profils.'),
    'progress_message' => t('Traitement @current sur @total.'),
    'error_message' => t('Le batch de migraiton des profils a échoué.'),
  );
  batch_set($batch);
  batch_process('admin/migration');
}
function dfr_migration_migrate_profiles_batch_finished() {
  drupal_set_message('Migration des utilisateurs terminée.');
  return '';
}

/**
 * Migrate the user profiles to D7.
 * The content of the user profile is stored in the content profile fields
 * content.
 * We need to fetch those values and saved them in the user profile fields.
 */
function dfr_migration_migrate_profiles_batch(&$context) {
  $limit = 100;
  if (empty($context['sandbox']['progress'])) {
    // Initialize batch update information.
    $context['sandbox']['progress'] = 0;
    $count = db_select('node', 'n')->condition('n.type', 'profile', '=')->countQuery()->execute()->fetchField();
    $context['sandbox']['max'] = $count;
  }

  // Fetch the existing user profiles nid + vid.
  $query = db_select('node', 'n');
  $query->condition('n.type', 'profile', '=')
      ->fields('n', array('nid', 'vid', 'uid'))
      ->range($context['sandbox']['progress'], $limit);
  $result = $query->execute();
  $user_ids = array();
  foreach ($result as $user) {
    $user_ids[$user->uid] = $user;
  }
  if (count($user_ids) == 0) {
    watchdog('migration dfr7', 'Range: ' . $context['sandbox']['progress'] . ' - ' . $limit, WATCHDOG_ERROR);
  }
  // Load the users and extract the old profiles data.
  $users = entity_load('user', array_keys($user_ids));
  foreach ($users as $user) {
    $query_profile = db_select('content_type_profile', 'ctp');
    $query_profile->condition('ctp.nid', $user_ids[$user->uid]->nid, '=')
        ->condition('ctp.vid', $user_ids[$user->uid]->vid, '=')
        ->fields('ctp', array(
      'field_icq_value',
      'field_jabber_value',
      'field_link_url',
      'field_link_title',
      'field_link_attributes',
      'field_msn_email',
      'field_nickname_value',
      'field_picture_fid',
      'field_picture_list',
      'field_picture_data',
      'field_realname_value',
      'field_company_nid',
    ));
    $query_profile->leftJoin('field_data_body', 'body', 'ctp.nid = body.entity_id AND ctp.vid = body.revision_id');
    $query_profile->fields('body', array('body_value'));
    $result_profile = $query_profile->execute();
    $content_profile_user = $result_profile->fetch();

    // Set new values in destination fields.
    // Let's define a flexible structure to easily store values in the new user
    // entity.
    // The values are arrays with two keys:
    //   - key: Field's name where to store the value (from the user entity
    //     point of view),
    //   - value: The value of the field to save.
    $classic_fields = array(
      array(
        'key' => 'field_icq',
        'value' => $content_profile_user->field_icq_value,
      ),
      array(
        'key' => 'field_jabber',
        'value' => $content_profile_user->field_jabber_value,
      ),
      array(
        'key' => 'field_nickname',
        'value' => $content_profile_user->field_nickname_value,
      ),
      array(
        'key' => 'field_realname',
        'value' => $content_profile_user->field_realname_value,
      ),
      array(
        'key' => 'field_biography',
        'value' => $content_profile_user->body_value,
      ),
    );
    foreach ($classic_fields as $field) {
      $user->$field['key'] = array(
        LANGUAGE_NONE => array(
          array(
            'value' => $field['value'],
            'format' => NULL,
            'safe_value' => check_plain($field['value']),
          ),
        ),
      );
    }

    // Handle the special structure of the msn email field.
    $user->field_msn = array(
      LANGUAGE_NONE => array(
        array(
          'email' => $content_profile_user->field_msn_email,
        ),
      ),
    );

    // Handle the special structure of the website field.
    $user->field_website = array(
      LANGUAGE_NONE => array(
        array(
          'url' => $content_profile_user->field_link_url,
          'title' => $content_profile_user->field_link_title,
          'attributes' => unserialize($content_profile_user->field_link_attributes),
        ),
      ),
    );

    // Handle the special structure of the company field.
    $user->field_company = array(
      LANGUAGE_NONE => array(
        array(
          'nid' => $content_profile_user->field_company_nid,
        ),
      ),
    );

    // Handle the special structure of the picture field.
    if ($content_profile_user->field_picture_fid &&
        ($profile_picture = file_load($content_profile_user->field_picture_fid)))
    {
      $user->field_picture = array(
        LANGUAGE_NONE => array(
          (array)$profile_picture,
        ),
      );
    }
    else {
      $user->field_picture = array(
        LANGUAGE_NONE => array(
          0 => array(
            'fid' => variable_get('drupalfr_user_default_picture', 0),
          ),
        ),
      );
    }
    // Fetch the events the user attended.
    $query_events = db_select('content_field_events', 'cfe');
    $query_events->condition('cfe.nid', $user_ids[$user->uid]->nid, '=')
        ->condition('cfe.vid', $user_ids[$user->uid]->vid, '=')
        ->fields('cfe', array(
      'delta',
      'field_events_value',
    ));
    $result_events = $query_events->execute();
    $user_events = array();
    foreach ($result_events as $event) {
      $user_events[LANGUAGE_NONE][] = array('value' => $event->field_events_value);
    }
    $user->field_events = $user_events;
    entity_save('user', $user);

    // Update the batch progression.
    $context['sandbox']['progress']++;
    $context['message'] = $context['sandbox']['progress'] . ' sur ' . $context['sandbox']['max'];
  }
  $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
}

/**
 * Implements hook_content_migrate_data_record_alter().
 */
function dfr_migration_content_migrate_data_record_alter(&$record, &$field, &$instance) {
  // The options widget for fields with select lists are kind of screwing
  // the match on the key/value. We are simply fetching the right value
  // based on the record / instance.
  if (($instance['widget_type'] == 'optionwidgets_buttons') || ($instance['widget_type'] == 'optionwidgets_select')) {
    $field_name = $instance['field_name'] . '_value';
    $key = $record[$field_name];
    $allowed_values_keys = array_flip($field['settings']['allowed_values']);
    $record[$field_name] = $allowed_values_keys[$key];
  }
}
