<?php

/**
 * Updates 'doc' node type configuration.
 */
function dfr_documentation_update_7000() {
  variable_set('node_submitted_doc', 0);

  module_load_include('inc', 'field', 'field.info');
  $instances = field_info_instances('node', 'doc');

  foreach ($instances as $field_name => $instance) {

    // Hide all fields except body
    if ('body' !== $field_name) {
      $instance['display']['teaser']['type'] = 'hidden';
    }

    field_update_instance($instance);
  }
}

