<?php

/**
 * @file
 * Code for the dfr_emploi feature.
 */

include_once 'dfr_documentation.features.inc';

/**
 * Implements hook_menu().
 */
function dfr_documentation_menu() {
  $items = array();
  $items['documentation'] = array(
    'title' => 'Documentation',
    'page callback' => 'dfr_documentation_page',
    'access arguments' => array('access content'),
    'menu_name' => 'primary-links',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Callback for documentation page
 */
function dfr_documentation_page() {
  $books = node_load_multiple(array(4395, 5037, 56, 9619, 4));
  return array(
    'books' => array(
      '#prefix' => '<div id="documentation">',
      '#suffix' => '</div>',
      'nodes' => entity_view('node', $books, 'teaser')
    ),
  );
}


/**
 * Implements hook_field_extra_fields().
 */
function dfr_documentation_field_extra_fields() {
  $extra['node']['doc'] = array(
    'display' => array(
      'book_children' => array(
        'label' => t("Book children"),
        'description' => t("Links to book children."),
        'weight' => 10, // Default weight
      ),
    )
  );
  return $extra;
}
 
 
/**
 * Implements hook_node_view().
 */
function dfr_documentation_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'doc') {
    // Add extra field render array to node content
    $node->content['book_children'] = array(
      '#markup' => book_children($node->book),
    );
  }
}

