<?php

/**
 * Implements hook_menu().
 */
function dfr_documentation_menu() {
  $items = array();
  $items['documentation'] = array(
    'title' => 'Documentation',
    'page callback' => 'dfr_documentation_page',
    'access arguments' => array('access content'),
    'menu_name' => 'primary-links',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function dfr_documentation_page() {
  $output = array(
    'books' => array(
      '#prefix' => '<div id="documentation">',
      '#suffix' => '</div>' 
    )
  );

  $books = node_load_multiple(array(4395, 5037, 56, 9619, 4));
  foreach ($books as $book) {
    $body = field_get_items('node', $book, 'body');
    $output['books']['book-'.$book->nid] = array(
      '#prefix' => '<div class="book book-'.$book->nid.'">', '#suffix'=>'</div>',
      'title' => array(
        '#markup' => '<h2>'. l($book->title, 'node/'. $nbook->nid) .'</h2>'
      ),
      'summary' => array(
        '#markup' => '<p>'. text_summary($body[0]['value']) .'</p>'
      ),
      'children' => array(
        '#markup' => book_children($book->book)
      )
    );
  }
  return $output;
}

