#!/usr/bin/env bash

CURRENT_SITE_DRUSH_ALIAS="DRUPAL_SITE_${DRUPAL_SITE^^}_DRUSH_ALIAS"

echo -e "${COLOR_LIGHT_GREEN}${DRUPAL_SITE}: Run CRON.${COLOR_NC}"
$DRUSH "${!CURRENT_SITE_DRUSH_ALIAS}" core:cron >> "${DRUPAL_CRON_LOG_FILE_PATH}" 2>&1
