<?php

/**
 * @file
 * Contains hook implementations for drupalfr_local_group module.
 */

/**
 * Implements hook_preprocess_node().
 */
function drupalfr_local_group_preprocess_node(&$variables) {
  // Prepare tweets on local group page.
  if ($variables['view_mode'] == 'full') {
    /** @var \Drupal\node\NodeInterface $node */
    $node = $variables['node'];
    if ($node->bundle() == 'local_group' && $node->hasField('field_twitter_account')) {
      $twitter_account = $node->get('field_twitter_account')->getValue();
      if (!empty($twitter_account)) {
        /** @var \Drupal\drupalfr_social\Service\TwitterServiceInterface $twitter_service */
        $twitter_service = \Drupal::service('drupalfr_social.twitter');

        $statuses = $twitter_service->getStatuses('statuses/user_timeline', [
          'screen_name' => $twitter_account[0]['value'],
          'count' => 3,
          'exclude_replies' => FALSE,
        ]);

        if (!empty($statuses)) {
          $variables['local_group_tweets'] = [
            '#theme' => 'drupalfr_social_twitter_statuses',
            '#statuses' => $statuses,
            '#cache' => [
              // 15 minutes.
              'max-age' => '900',
            ],
          ];
        }
      }
    }
  }
}
