name: Drupal8 Deploy

on:
  push:
    branches: [ 8.x-1.x ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains( github.ref, '8.x-1.x')
    steps:
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.ssh_private_key }}
    - uses: actions/checkout@v2
    - name: Disable StrictHostKeyChecking
      run: |
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - name: Deploy website
      env:
        GIT_URL: ${{ secrets.git_url }}
      run: |
        git remote add upstream $GIT_URL
        git fetch upstream
        git checkout upstream/test_ci
        git merge origin/8.x-1.x -m "Merge from github"
        git push upstream/develop
