name: Drupal8 Deploy

on:
  push:
    branches: [ 8.x-1.x ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains( github.ref, '8.x-1.x')
    steps:    
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.ssh_private_key }}
    - name: Clone Drupalfr Project
      run: |
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        git config --global user.email "github@drupal.fr"
        git config --global user.name "Github"
        git clone https://github.com/Drupal-FR/site-drupalfr.git
    - name: Deploy website to develop plateform
      env:
        GIT_URL: ${{ secrets.git_url }}
      run: |
        cd site-drupalfr
        git remote add upstream $GIT_URL
        git fetch upstream
        git checkout upstream/develop -b deploy
        git merge origin/8.x-1.x -m "Merge from github" --allow-unrelated-histories
        git push -f upstream deploy:develop
