name: Drupal8 Pr

on:
  pull_request:
    branches: [ 8.x-1.x ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
    - uses: actions/checkout@v2
    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-progress
    - name: Run phpcs
      run: |
        ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer/
        ./vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md' www/modules/custom/
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install npm packages
      run: |
        cd www/themes/custom/drupal_france/
        npm i
    - name: Run Gulp sass lint
      run: |
       cd www/themes/custom/drupal_france/
       ./node_modules/gulp/bin/gulp.js lint
