<?php

function tweetbutton_init(){
  drupal_set_html_head('<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>');
}

function tweetbutton_link($type, $node = NULL, $teaser = FALSE) {
  $links = array();

  if ($type == 'node' && $node->type != 'page' && $teaser == 0) {
    $links['tweetbutton'] = array(
      'title' => 'Tweet',
      'href' => 'http://twitter.com/share',
      'attributes' => array('class' => 'twitter-share-button','data-count' => 'horizontal'),
      'weight' => -10,
    );
  }

  return $links;
}

function tweetbutton_link_alter(&$links) {
  if (isset($links['tweetbutton'])) {
    $button = $links['tweetbutton'];
    unset($links['tweetbutton']);
    $links = array('tweetbutton' => $button) + $links;
  }
}

